#!/bin/bash

set -e

# Example usage:
# - use local APT cache, and set-up serial console
#   MIRROR="http://localhost:9999/debian" GRUB_CMDLINE="console=tty0 console=ttyS0" ./qemu-debian-create-image foo.qcow2 myhostname stretch
# - use local APT cache, and set-up serial console, no network interface configuration (default is DHCP)
#   MIRROR="http://localhost:9999/debian" GRUB_CMDLINE="console=tty0 console=ttyS0" ETH_DEVICE="no" ./qemu-debian-create-image foo.qcow2 myhostname stretch
# Then start with:
#  kvm -hda foo.img -net nic -net user -m 256 -serial stdio

# Configs overwritable via environment variables
VSYSTEM=${VSYSTEM:=qemu}						# Either 'qemu' or 'kvm'
FLAVOUR=${FLAVOUR:=debian}					# Either 'debian' or 'ubuntu'
INCLUDES=${INCLUDES:="less,vim,sudo,openssh-server,dbus,net-tools,traceroute,mtr-tiny,telnet,wget,curl,ethtool"}
MIRROR=${MIRROR:="https://mirrors.tuna.tsinghua.edu.cn/debian"}
#MIRROR=${MIRROR:="http://localhost:3142/debian"}
#MIRROR=${MIRROR:="http://archive.ubuntu.com/ubuntu/"}
#MIRROR=${MIRROR:="http://localhost:3142/ubuntu"}
ARCH=${ARCH:=amd64}
APT_CACHER=${APT_CACHER:=no}
IMGSIZE=${IMGSIZE:=30G}
ROOTPASSWD=${ROOTPASSWD:=root}
DISKNAME=${DISKNAME:=sda}
GRUB_CMDLINE=${GRUB_CMDLINE:=console=ttyS0}
ETH_DEVICE=${ETH_DEVICE:=ens3}

clean_debian() {
	[ "$MNT_DIR" != "" ] && chroot $MNT_DIR umount /proc/ /sys/ /dev/ /boot/EFI
	sleep 1s
	[ "$MNT_DIR" != "" ] && umount $MNT_DIR
	sleep 1s
	[ "$DISK" != "" ] && $VSYSTEM-nbd -d $DISK
	sleep 1s
	[ "$MNT_DIR" != "" ] && rm -r $MNT_DIR
}

fail() {
	clean_debian
	echo ""
	echo "FAILED: $1"
	exit 1
}

cancel() {
	fail "CTRL-C detected"
}

if [ $# -lt 3 ]
then
	echo "author: Kamil Trzcinski (http://ayufan.eu)"
	echo "license: GPL"
	echo "usage: $0 <image-file> <hostname> <release> [optional debootstrap args]" 1>&2
	exit 1
fi

FILE=$1
HOSTNAME=$2
RELEASE=$3
shift 3

trap cancel INT

echo "Installing $RELEASE into $FILE..."

MNT_DIR=`tempfile`
rm $MNT_DIR
mkdir $MNT_DIR
#MNT_DIR="/mnt"
DISK=

# add apt cacher for faster rebuilds, runs on 3142
if [ "$APT_CACHER" == "yes" ]; then
    echo "Installing apt-cacher-ng for fast rebuilds"
    apt-get install apt-cacher-ng
fi

if [ ! -f $FILE ]; then
    echo "Creating $FILE"
    $VSYSTEM-img create -f qcow2 $FILE $IMGSIZE
fi

if [ $FLAVOUR == "debian" ]; then
    BOOT_PKG="linux-image-$ARCH grub-pc"
elif [ $FLAVOUR == "ubuntu" ]; then
    BOOT_PKG="linux-image-generic grub-pc"
fi

echo "Looking for nbd device..."

modprobe nbd max_part=16 || fail "failed to load nbd module into kernel"

for i in /dev/nbd*
do
	if $VSYSTEM-nbd -c $i $FILE
	then
		DISK=$i
		break
	fi
done
#DISK=/dev/nbd0

[ "$DISK" == "" ] && fail "no nbd device available"

echo "Connected $FILE to $DISK"

# New sfdisk on stretch doesn't do -D and -uM anymore
echo "Partitioning $DISK..."
sgdisk --clear -n 0::+1m -t 1:EF02 -n 0::+100m -t 2:EF00 -n 0::+1024m -t 3:8200 -n 0:: -t 4:8300 -h 2:4 -p $DISK

echo "Creating boot partition..."
mkfs.vfat -F32 ${DISK}p2 || fail "cannot create /boot/EFI fat32"

echo "Creating swap partition..."
mkswap  ${DISK}p3 || fail "cannot create swap partition"

echo "Creating root partition..."
mkfs.ext4 -q ${DISK}p4 || fail "cannot create / ext4"

echo "Mounting root partition..."
mount ${DISK}p4 $MNT_DIR || fail "cannot mount /"
mkdir -p $MNT_DIR/boot/EFI
mount ${DISK}p2 $MNT_DIR/boot/EFI || fail "cannot mount /"

echo "Installing Debian $RELEASE..."
debootstrap --include=$INCLUDES $* $RELEASE $MNT_DIR $MIRROR || fail "cannot install $RELEASE into $DISK"

SWAP=`blkid | grep ${DISK}p3 | cut -d ' ' -f2`
EFI=`blkid | grep ${DISK}p2 | cut -d ' ' -f2`
ROOT=`blkid | grep ${DISK}p4 | cut -d ' ' -f2`
echo "Configuring system..."
cat <<EOF > $MNT_DIR/etc/fstab
$EFI  /boot/EFI  vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro   0 2
$ROOT /                   ext4    errors=remount-ro 0       1
$SWAP none            swap            defaults        0 0
EOF

echo $HOSTNAME > $MNT_DIR/etc/hostname

cat <<EOF > $MNT_DIR/etc/hosts
127.0.0.1       localhost
127.0.1.1 		$HOSTNAME
# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

cat <<EOF > $MNT_DIR/etc/network/interfaces
auto lo
iface lo inet loopback
EOF
if [ "$ETH_DEVICE" != "no" ]; then
	cat <<EOF > $MNT_DIR/etc/network/interfaces
auto ${ETH_DEVICE}
iface ${ETH_DEVICE} inet dhcp
EOF
fi

mount --bind /dev/ $MNT_DIR/dev || fail "cannot bind /dev"
chroot $MNT_DIR mount -t proc none /proc || fail "cannot mount /proc"
chroot $MNT_DIR mount -t sysfs none /sys || fail "cannot mount /sys"
LANG=C DEBIAN_FRONTEND=noninteractive chroot $MNT_DIR apt-get install -y --force-yes -q $BOOT_PKG || fail "cannot install $BOOT_PKG"

chroot $MNT_DIR grub-install --skip-fs-probe $DISK || fail "cannot install grub"
sed -i "s|GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT=\"${GRUB_CMDLINE}\"|" $MNT_DIR/etc/default/grub
sed -i "s|GRUB_TIMEOUT=5|GRUB_TIMEOUT=1|" $MNT_DIR/etc/default/grub
echo 'GRUB_DISABLE_OS_PROBER=true' >> $MNT_DIR/etc/default/grub
chroot $MNT_DIR update-grub || fail "cannot update grub"
chroot $MNT_DIR apt-get clean || fail "unable to clean apt cache"
chroot $MNT_DIR rm -rf /var/lib/apt/lists/*

sed -i "s/root=[^ \t]*/root=$ROOT/g" $MNT_DIR/boot/grub/grub.cfg

# Set root password
echo "root:${ROOTPASSWD}" | chroot $MNT_DIR chpasswd

echo "Finishing grub installation..."
grub-install $DISk --target=x86_64-efi --efi-directory=$MNT_DIR/boot/EFI --boot-directory=$MNT_DIR/boot  || fail "cannot install grub-efi"

echo "SUCCESS!"
clean_debian

echo "Shrinking qcow2 file..."
qemu-img convert -O qcow2 $FILE $FILE.new
mv $FILE.new $FILE

exit 0
